jenkins-x.yml
scripts/update-bot.sh

Automatically update the dev-env-base version in dev-env when it is released

feat: Auto update dev-env with base version

---

scripts/update-bot.sh

fix: Use https url for update-bot repo

---

jenkins-x.yml

fix: Use jx-builder image for update-bot

---

scripts/update-bot.sh

fix: update-bot jx path

---

Dockerfile.go-alpine

chore: Update base image to 1.12.6-alpine3.10

---

env/bashrc

feat: add bash completion to jx

---

Dockerfile.go-alpine
README.md

feat: adding terraform vim plugin

---

Dockerfile.go-alpine

feat: added gcloud alpha and beta components

---

Dockerfile.go-alpine

Install https://github.com/23andMe/Yamale

feat: install yamale

---

Dockerfile.go-alpine
Makefile

feat: Improving how multistaged images are built

---

Dockerfile.go-alpine
Makefile

Reverts jenkins-x/dev-env-base#85

fix: Revert "feat: Improving how multistaged images are built"

---

env/bashrc
env/tmux.conf.local

feat: now able to have a k8s context per window session

---

jenkins-x.yml

this allows `jx step create pr` to reuse them

chore: create release notes first

---

jenkins-x.yml

chore: Add memory requests/limits to pipeline

---

env/bashrc
env/tmux.conf.local

revert: removed kube session per tmux window

---

jenkins-x.yml

fix: add missing pipeline build for zsh container base

---

scripts/update-bot.sh

fix: update the dev-env-zsh file with the new version

---

env/bash/tmux.conf.local

fix: update cluster name

---

Dockerfile.go-alpine

feat: added vault client and diffutils

---

Dockerfile.go-alpine

feat: add the safe vault client

---

Dockerfile.go-alpine
Makefile

Taken the unpacked image size down from 5GB to ~2.2GB

fix: reduced image size

---

Dockerfile.go-alpine

feat: added remote debug port for dlv

---

Dockerfile.go-alpine

chore: helm 2.14.1

---

Dockerfile.go-alpine
jenkins-x.yml

chore: downgrade golang to 1.12.17-alpine3.11

---

Dockerfile.go-alpine
Makefile

chore: specify gopls version - go 1.12 compatible

---

jenkins-x.yml

chore: name the pr steps
